### ISSUE TITLE
RIS Attributes

### ISSUE THREAD

**Issue by rendermouse** [bsavery/PRMan-for-Blender#105]
I'm considering wiring up more of the RIS object attributes.

Would you like a Ray Tracing attributes panel to go with the Shading and Visibility panels?  It would contain maxdiffusedepth, maxspeculardepth, displacements (onoff), bias, autobias (onoff), samplemotion, decimationrate and intersectpriority.

Are there any other RIS per-object attributes not set by other panels?

**Comment by MWY3510** [comment]
This sounds like a great idea. Just as a conformity thing I think that any displacement options should go in the materials tab to make it easier to find. I wish you great success on this enhancement.

MWY3510

**Comment by bsavery** [comment]
Really great to expose these. But. The other thing to keep in mind here is
that probably 80% of the time people might not need these. Keeping the yo
simple or hiding the "expert" attributes is usually a good idea. Otherwise
you get people clicking buttons just to try things and possibly making
their scene worse. Even just keeping a panel closed by default sometimes is
enough

On Sunday, August 9, 2015, MWY3510 <notifications@github.com> wrote:

> This sounds like a great idea. Just as a conformity thing I think that any
> displacement options should go in the materials tab to make it easier to
> find. I wish you great success on this enhancement.
>
> MWY3510
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/105#issuecomment-129218420>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by rendermouse** [comment]
Brian, that's why I was asking. As I was reading through the docs for some of these attributes, I was wondering if it was even worth exposing these in the UI, or if it would just confuse people.

**Comment by MWY3510** [comment]
I think that this should be included. Even though only advanced users will use it. An option would be to hide it under a button toggle in a panel. This would allow you to put some text warning about how these are options that should not be messed with unless you know what you are doing.

**Comment by rendermouse** [comment]
Here's a pic of what the new attributes panels look like at the moment. Checking the "Override Ray Tracing" box unlocks the rest of the panel. I only output attributes that deviate from the defaults to save space in the RIB.  MWY, I put the true displacement setting in this panel because it applies to the entire object, regardless of material, and is grouped with the rest of these attributes in the docs. 

I am testing these to ensure that they all output properly to the RIB (so far it looks good), but I wanted to go ahead and show you what the panels look like.

![image](https://cloud.githubusercontent.com/assets/1102555/9158001/60a27c28-3edd-11e5-895d-b1ff29619aee.png)

**Comment by MWY3510** [comment]
Looks good. Keep up the great work. Also is the panel closed by default?

**Comment by rendermouse** [comment]
Yes, The Ray Trace panel is closed by default.

**Comment by bsavery** [comment]
Great start.  He's a few thoughts I have.
1.  The holdout object should really be in the shading section of the UI. (my bad)  But on the other hand I would consider it a "standard" attribute while the other shading attributes kinda are more "export".
2.  The shading rate, motion approx, focus approx can be more expert attributes.
3.  Does exposing the shading interpolation even make sense?  Actually I'm fairly certain it doesn't work in RIS mode when set to constant since it's related to shading micropolygons.  Who would actually use this?  
4.  Remember in RIS the visitibilty attributes are Camera, indirect, transmision.  Specular and Diffuse are deprecated.  I'm not sure how many people would know what the midpoint filter does?

5.  I appreciate the ray tracing attributes greyed out by default, the label warning might be a bit overkill though.  Probably enough to put the warning in the tooltip of the override checkbox IMO.
6.  True Displacements = Trace displacements?  If so it is on by default.

Looks good!

**Comment by rendermouse** [comment]
Thanks for the feedback! Consider the following changes:

I could move Holdout to the Shading panel, but...
If I do that, and move shading rate, motion approx & focus approx to Ray Tracing (expert) panel, Shading panel would only contain Holdout and Holdout group. Perhaps if we did this, we could move Motion Segments into the Shading panel as well? It seems like a logical place for it.

Or...I could move Holdout to the Shading panel, and add an override checkbox in the Shading Panel that applies to shading rate, motion approx and focus approx as a group like the Ray Tracing panel in the above screenshot.

The other changes Brian mentioned make perfect sense, and I can fix those up.

**Comment by bsavery** [comment]
I think the second option sounds perfect!  Motion factor and shading rate are related to shading

**Comment by rendermouse** [comment]
Here's the new set of attribute panels, and it feels much improved. I am not sure if Trace Sets should stay in Visibility panel, I'll let you guys be the judge of that. I updated [my repo](https://github.com/rendermouse/PRMan-for-Blender) if you want to try it out. I didn't want to submit a pull request until you reviewed the changes.

![image](https://cloud.githubusercontent.com/assets/1102555/9188543/7c10d2ba-3fab-11e5-9e0c-6c03e0d98eee.png)

**Comment by bsavery** [comment]
I'd say put the trace sets under Ray Tracing... and not under the greyed out part.

**Comment by rendermouse** [comment]
Ray Tracing panel now looks like this in my updated repo:
![image](https://cloud.githubusercontent.com/assets/1102555/9297445/980075e0-446d-11e5-9bf4-f96e33904a33.png)

**Comment by bsavery** [comment]
That looks great. I should have mentioned... There's not really a way to control trace set in RIS with the default BXDF's right now, so maybe could hide those.

Also minor issue but I'd rename Ray Origin Auto Bias to "Raytrace Auto bias" But other than I'd say push it to master.

**Comment by rendermouse** [comment]
Brian, do you mean hide the Group setting? Also hide Include/Exclude?

**Comment by bsavery** [comment]
Along the lines of "advanced" settings I moved things around in the render settings to make it simpler and hide the settings that 99% don't use:

Move Renderman output -> output and move that panel up. 
Collapse integrator settings, put just sampling settings in the sampling panel
move shading rate, bucket order, pixel filter, and others to the advanced tab, motivation:  most people won't use these.
![screen shot 2015-08-19 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/1892220/9370253/b9e9adee-4683-11e5-8a0c-db147a95f99f.png)

**Comment by bsavery** [comment]
Can I integrate your changes today?

**Comment by bsavery** [comment]
I merged the attribute changes.

**Comment by rendermouse** [comment]
OK. Thanks!
