### ISSUE TITLE
Smoke is not rendered

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#120]
I modified a bit this file from siggraph: https://www.dropbox.com/sh/nwlflkkyf9yvajp/AACx1YCa6ECxLYlgAWLBcqE1a/smoke_fire?dl=0

But smoke is not rendered now. 
![_008](https://cloud.githubusercontent.com/assets/2251298/9443500/092879ee-4a8a-11e5-80c7-f29c14e279dc.png)

**Comment by bsavery** [comment]
Works fine for me.... Did you rewind and play in timeline?

**Comment by mifth** [comment]
You are too fast for closing issues. :)
I orgot to add my modified version of the file: https://dl.dropboxusercontent.com/u/26887202/blender/fire_monkey_matte2.blend

Try this one. It does not render smoke.
I cannot reopen the issue.

**Comment by bsavery** [comment]
Hmmm I downloaded your first file and hit render. Sorry about that I'll
take a look at the second file

On Tuesday, August 25, 2015, mifth <notifications@github.com> wrote:

> You are too fast for closing issues. :)
> I orgot to add my modified version of the file:
> https://dl.dropboxusercontent.com/u/26887202/blender/fire_monkey_matte2.blend
>
> Try this one. It does not render smoke.
> I cannot reopen the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/120#issuecomment-134526123>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by mifth** [comment]
The first file is from your dropbox.

**Comment by bsavery** [comment]
Right. Just wasn't clear from your screenshot if and what you modified.
Like I said will take a look at your file!

On Tuesday, August 25, 2015, mifth <notifications@github.com> wrote:

> The first file is from your dropbox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/120#issuecomment-134563764>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment]
Your file as well is rendering for me.  Can you explain what you're changing?  
![untitled](https://cloud.githubusercontent.com/assets/1892220/9475583/633af8f2-4b1c-11e5-8064-2ad631f9cf5c.jpg)

**Comment by mifth** [comment]
I'll make a video when i get to my machine. About in 10 hours. Sorry.
I'm on a phone right now.

**Comment by mifth** [comment]
Here is the scene video:
http://youtu.be/SQhM699bhuw

**Comment by bsavery** [comment]
Ah ok.  I think I see what's going on here.  So this is related to the "rib caching" mechanism.  Two things to note:

1.  Non-animated rib archives go under the ~/Documents/prman_for_blender/SCENE/archives/static directory and animated objects under the ~/Documents/prman_for_blender/SCENE/archives/FRAME_NUMBER directory.  

2. We detect whether objects are changed since they were last rendered, and if not, we don't re-generate the rib.  

So what's happening is that the smoke object is incorrectly being seen as static (since the bounding box isn't animating) so the archive is going under the static/ directory.  And then the archive isn't being updated the next time you render.  This should be a simple fix I can do today, but as a quick work around you can go to the "Advanced" Scene settings and uncheck the "Cache Rib Gen" checkbox.

**Comment by mifth** [comment]
Great that you found it. No rush. I can wait for the fix.

**Comment by bsavery** [comment]
fixed with latest.
