### ISSUE TITLE
Support for bevelled Curve objects?

### ISSUE THREAD

**Issue by zeffii** [bsavery/PRMan-for-Blender#15]
Firstly, super neat work :)

I get quite a few errors, suggesting that I should convert the bevelled curves in my model to a mesh, rather than saying 'object has no faces' perhaps it should enumerate the objects and tell the user to convert the curves to meshes before sending to prman, (or generate an intermediate .blend with Curves already converted to mesh?)

**Comment by zeffii** [comment]
See this model: (Free to use Non Commercially, else seek contact with me)
(spot rendered in Cycles: https://www.dropbox.com/s/x2rstnxi6wtrd7k/f48_total.png?dl=0 )

the .blend  https://www.dropbox.com/s/52263yvktcxq139/madmoto20_MODEL.blend?dl=0

**Comment by AtomicPerception** [comment]
I just wrote a fix for this in my fork. The problem was in the style of the modeling. If you actually examine those objects and press the TAB key you will see that the do indeed have no faces, just edges and verts. The faces are being created by the mirror modifier. I have put a check in the AddOn which now correctly detects such modling and includes those style of objects for export as well.

**Comment by zeffii** [comment]
cool, thanks for having a look! I see now!

**Comment by bsavery** [comment]
AtomicP... can you do a pull request to integrate that change?
