### ISSUE TITLE
 license error ?

### ISSUE THREAD

**Issue by dezaxe** [bsavery/PRMan-for-Blender#194]
Hello everyone !
Small problem that causes me frustration unnamed.
I installed renderman, no worries. I installed the add-on, no worries. But when I run a report in blender with renderman, Error! Renderman: Exited!
I'm going to see applications installed when installing renderman and I can see LocalQueue, Slim and It. When I run them as error messages.
![capture](https://cloud.githubusercontent.com/assets/17174179/12980770/31c5a554-d0de-11e5-9d69-42d9701964ee.PNG)
If someone could get me out, help!
Thank you in advance,

**Comment by bsavery** [comment]
This is really a RenderMan issue rather than the addon... normally best place is to post them here: https://renderman.pixar.com/forum/forumdisplay.php?s=&forumid=161

Your best bet is to re-run the installer and see if you get an error getting the license?  Or I'd need your renderman forum username to look you up in the license database and see what's going on.

**Comment by dezaxe** [comment]
Thank you, I'll post the renderman forum.
My username on Renderman is "Dézaxé".
I have already reinstall but I have the same errors.
Thanks again,

**Comment by bsavery** [comment]
Fixed, accents in name.

**Comment by dezaxe** [comment]
Merci ;)
