### ISSUE TITLE
Rendering wont start

### ISSUE THREAD

**Issue by Toonyx** [bsavery/PRMan-for-Blender#213]
Hello there,
After about 5 hours of searching and trying out stuff that I found I decided to search for help here.
So after about 2 hours I finally got the addon for Renderman in Blender installed and tried out to render a simple scene. It was only the standard cube with a glass material standing on a plane with a light above them. i didn´t touch the properties of any other option.
When I pressed render it said Pr Man exited so I searched for the problem and found al the stuff about ascii characters or "it" starting manually but I couldn´t find the roblem on my own. 
There are three different outcomes when I hit render:
1: The message "prman exited"
2: The program just closes without any message at all
3: a message in blender appears (only after the first problem has already appeared and I pres render again) 
![image](https://cloud.githubusercontent.com/assets/17809937/13728305/13cadbca-e914-11e5-87e3-bc28978d8c3f.png)

I have reinstalled both, blender and renderman server pro 20.7. 
I even reinstalled them a third time to ahve both on the same hard drive beacause of some weird maybe bug fixing reason... who knows.
I tried all 3 of the output files I gave it manually and output directory etc but now I am out of Ideas.

Hope you can help me, thanks in advance.
Cheers

**Comment by bsavery** [comment]
What did you put in the Image path in the global settings?  The default is $OUT/images/{scene}_####.{file_type}  it seems to imply you put something with an E: in there?

**Comment by Toonyx** [comment]
I installed and saved everything on my external drive "E" which is connected via USB 3.0
Previously I had the installation on D which is my internal hard drive. Since it didn´t worked there I decided to just try out my external one. 
And "C" is a SSD which I only use for booting the system.

**Comment by bsavery** [comment]
Oh ok.  So a bit of background how the addon works, it creates some intermediary files, textures and RIB files that you most likely don't need to worry about.  These are made in the $OUT directory (think of it like the project directory in Maya.  Anyway so the error you see is because the addon is trying to make a path relative to the $OUT directory for your image.  Normally people put the output images where the intemediary files are, but it's fine not too!  Unfortunately on windows relative paths between drives don't work.  

So here's what you probably want to do:
1.  In the User preferences for the RenderMan addon there's the $OUT variable.  You probably want to set that to your D: directory, currently it includes your home directory which is on C:\Users\Joshi....
OR
2.  Change the image output to include $OUT  
or both.  

Really we maybe wan't to consider changing whether the $OUT directory should be set to some temp dir and just the image should go to wherever blender normally does it.  But for not either of the above should be a workaround for you.

**Comment by Toonyx** [comment]
Ok, so I am not 100% sure if I correctly did what you told me so i am just posting it again since what I tried didn´t work out yet.

So this is what the default user settings looked like:
![unbenannt](https://cloud.githubusercontent.com/assets/17809937/13736746/9f686064-e9b7-11e5-8a48-8b9541fdcb33.jpg)
So I changed the "Out (Output root)" to: "$OUT\blenderout"
Not sure if that is correct since it didn´t work. 

And also, in blender the original output looks like this:
![2](https://cloud.githubusercontent.com/assets/17809937/13736781/efba1d50-e9b7-11e5-967e-d62f63ac175a.jpg)
There the $OUT is already included by default.

According to your point "1", the only "C:\Users\Joshi...." directory is 
![3](https://cloud.githubusercontent.com/assets/17809937/13736841/7cf8cd88-e9b8-11e5-8352-4b13a025609d.jpg)
there. If that is what I am supposed to change, how do I do this since it is not a simple editable directory.

Cheers :)

**Comment by bsavery** [comment]
Still having issues?

**Comment by Toonyx** [comment]
Yes.
However I have tried running PRman with Blender on Linux which worked in a virtual machine but the performance was sub-par.

On the Windows side I have tried using reative paths(without spaces) to locate the binaries and for $out to no avail.
Since no pycache folders are created on Windows my best guess is that the scripts are not run properly.

**Comment by bsavery** [comment]
Hmmm.... I guess I'm confused.  I don't think the binary paths are used for anything anymore (they'll be removed).  Also what are your OUT settings and the scene settings for rib output and image path?

Brian

**Comment by bsavery** [comment]
Bump.  Did you check you $OUT setting in the addon prefences?
