### ISSUE TITLE
On gooseberry scene, some isues with multi-material objects

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#50]
WARNING:  ('export_objects: problem creating MESH [me_0-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_1-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_2-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_3-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_4-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_5-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_6-PIX_GEO-victor_head.002] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_2-PIX_GEO_watch] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_1-PIX_GEO_watch_ring] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_3-PIX_GEO_watch_ring] in memory.',)
WARNING:  ('export_objects: problem creating MESH [me_4-PIX_GEO_watch_ring] in memory.',)

I think multi-material rib gen MAY be able to be done without creating new objects.  This would improve ribgen times as well.

**Comment by AtomicPerception** [comment]
Can you attach or point to a link to the Gooseberry scene that is presenting the multi-material problem? I would like to try to re-create the error.

I do agree that creating new temporary objects is not the best way to handle multi-material.

**Comment by bsavery** [comment]
I used this scene:
https://gooseberry.blender.org/gooseberry-production-benchmark-file/

We already have the mesh data, I think we could call export_geometry or something directly with the original objects, just using the temp mesh data.

**Comment by bsavery** [comment]
Actually I was using just a few objects from that scene, Mainly the red hair guy.

**Comment by AtomicPerception** [comment]
Brian, after taking a look at the Gooseberry benchmark scene and the multi-material code I feel it is working as intended. What is going on here is that there are left over materials on the object with no faces mapped to them. This produces the warning. This was probably due to the fact the the hair, beard, eyebrows and lashes were originally just materials mapped to faces. Later in production the Gooseberry team replaced those with hair particle systems but failed to remove the material slots that were previously associated with those faces.

The slowdown in export in this scene is not the multi-material code, it is the particle system export.

**Comment by bsavery** [comment]
I'd agree on the scene export slowness being on particle systems.  

Hmm that sounds reasonable on the reason behind the multi material warning.  However that seems like a situation that should not cause a warning?  What do you think?

**Comment by AtomicPerception** [comment]
Correct, you can downgrade the message to INFO, if you like.
