### ISSUE TITLE
I am still having trouble. I went to env settings and created a PATH to rendermanproserver20 and still a trace back error.

### ISSUE THREAD

**Issue by PonchoVillegas** [bsavery/PRMan-for-Blender#51]
The guys at my company are really having trouble.
http://imgur.com/YfRTjTv

**Comment by bsavery** [comment]
You don't by any chance have a 32 bit version of blender installed do you?

**Comment by PonchoVillegas** [comment]
I haven't checked in this guy's computer. I will. Does 32 bit not work? What makes you think there's 32 bit blender on the computer.

**Comment by bsavery** [comment]
Actually I take that back.  It looks like from the error you copied the prman.py from the RenderMan Pro Server/bin directory to the addon directory.  Don't do that.

**Comment by PonchoVillegas** [comment]
Actually I downloaded the zip file, extracted all of it. And placed it in the blender addons folder. I own Renderman for Maya in PRman 19. I wanted PRman for blender to keep my teams workflow as short as possible. So I deleted everything related to Renderman, and redownloaded it. And that's when I got the error.

**Comment by PonchoVillegas** [comment]
I'm just not sure what to do, since I really am a fan of PRman and it's Ptex integration.I don't wanna keep bugging you guys ya know?

**Comment by MarshallRoss** [comment]
Addon doesn't work with PRMan 19, I think.

**Comment by MWY3510** [comment]
PonchoVillegas,

I think that MarshallRoss has the solution (it looks like the typical error
message for not finding the prman 20 python module). Also keep bringing any
problems you have. The way this add-on gets better is if the users find
flaws in it and report them.

MWY3510

**Comment by PonchoVillegas** [comment]
But I'm not using PRman 19. I deleted everything Renderman related then redownloaded Renderman 20. 
That's when I got this error.

**Comment by MWY3510** [comment]
Can I see what you have for the RMANTREE variable? Also do you have anything in the PYTHONPATH variable?

**Comment by bsavery** [comment]
Sorry, you have still have it configured wrong.  In the Renderman/bin folder there is a file called prman.py.  You moved this to your addon folder.  You can see that from the error in the lines I underlined.  Please delete your addons folder.  And remove your RMANTREE and PYTHONPATH variable.  Then reinstall the addon.  Start from scratch.

![yfrtjtv](https://cloud.githubusercontent.com/assets/1892220/8854886/2737f982-3117-11e5-921a-2624ded9b668.jpg)

**Comment by bsavery** [comment]
To be more clear.  There is not normally a prman.py file in the addons folder.

**Comment by AtomicPerception** [comment]
You also have to set the system PATH variable to include the path to the
bin folder of PRMan.

Like so...
"...;C:\Program Files\Pixar\RenderManProServer-20.1\bin;..."

**Comment by PonchoVillegas** [comment]
I created a variable called PATH and set it to C:\Program Files\Pixar\RenderManProServer-20.0\

**Comment by PonchoVillegas** [comment]
Right now I am redownloading blender. I deleted everything to start from scratch. I kept renderman 20 though.

**Comment by PonchoVillegas** [comment]
Editing the path variable to include bin. Let's see how this goes.

**Comment by bsavery** [comment]
Poncho.  I'd really like to help you here.  But I think we're just confusing you a bit.  Please take a second to stop and read the installation instructions before continuing:
https://github.com/bsavery/PRMan-for-Blender/blob/master/installation.txt

The main thing to read and understand here is that you DO NOT have to set any environment variables by default if you just install the RenderMan software.  "If you are installing PRMan to the standard location you shouldn't have to do anything!"  

However before you had your RMANTREE environment variable set to RenderMan 19.0 location which did not work because you need a 20.0 or later version of RenderMan.  That is why we suggested you change that.  To make it more simple for people in your situation I've fixed the latest version of the plugin to skip loading 19.0 and go to 20.0.  Additionally I think on windows that installing RenderMan 20.0 will set your RMANTREE variable correctly to 20.0.  You just need to reboot for it to take effect.

Please let me know if any of this isn't clear.

**Comment by PonchoVillegas** [comment]
Ok. I had deleted the addons folder and started from scratch. That didn't wprk and I got this error:
![error](https://cloud.githubusercontent.com/assets/12225954/8858283/d1c846d8-3133-11e5-9b44-1078aaa7bf87.jpeg)
So I repaired blender and tried again and got this:
![error2](https://cloud.githubusercontent.com/assets/12225954/8858348/2d659306-3134-11e5-90d3-8762903b4cbf.png)

**Comment by MWY3510** [comment]
PonchoVillegas,

It still looks like there is a problem with having prman.py in the addons folder. If you can go to C:\Users\Admin\AppData\Roming\Blender Foundation\Blender\2.25\scripts\

Then delete the addons folder you find there.
Hope this helps,
MWY3510

**Comment by PonchoVillegas** [comment]
Well I'll be damned! It works. Thanks for the help comrades. Sorry you had to put up with my lack of knowledge of programming. Anyways, thanks for the help. I'm marking this closed.
