### ISSUE TITLE
Strand rendering still has a hard limit and breaks.

### ISSUE THREAD

**Issue by MWY3510** [bsavery/PRMan-for-Blender#52]
I am working on it but a second person is welcome.

**Comment by bsavery** [comment]
I can take a look, but what do you mean by a "hard limit"

**Comment by MWY3510** [comment]
When the strand count goes above 2098 on any mesh the exporter receives only 10 vertices to use. This messes up the ri.curves function if I let it receive the data. Here is a picture.
![error](https://cloud.githubusercontent.com/assets/9410101/8860363/56ff4eba-3151-11e5-884b-c9cd659ac83f.jpg)

**Comment by bsavery** [comment]
Ah.  Does that have to do with the maxint on list size?

The sys.maxint constant was removed, since there is no longer a limit to the value of integers. However, sys.maxsize can be used as an integer larger than any practical list or string index. It conforms to the implementation’s “natural” integer size and is typically the same as sys.maxint in previous releases on the same platform (assuming the same build options).

https://docs.python.org/3.1/whatsnew/3.0.html#integers

Maybe if we get to a set of verts that big we should just export the ri.curve and start a new one ;)

**Comment by MWY3510** [comment]
Now that I should have expected (facepalm.) It makes sense now that you mention it. I think your solution of just exporting the data when it gets close and resting the list is the best option.

**Comment by bsavery** [comment]
I would actually just set a limit of 10000 vertices or so and reset after that.  Want me to code that up?

**Comment by MWY3510** [comment]
Thanks that would be great. My fork is a little crouded will all the osl stuff.
