### ISSUE TITLE
Export.py cleanup and rewrite

### ISSUE THREAD

**Issue by bsavery** [bsavery/PRMan-for-Blender#73]
The export code has gotten to be a bit of a mess.  I propose to rewrite it and simplify.  

Basically here's what I'm thinking: 
1.  Minimize scene updates and creating new meshes to what extent possible.
2.  Try to not pre - walk through scene.
3.  Do multi-materials "in line", i.e. don't create new meshes, fix uv issues:
https://github.com/bsavery/PRMan-for-Blender/issues/61

4.  Use "callbacks" for object types:
callbacks = { 'SPHERE': export_sphere,
                     'MESH': export_polygon_mesh,
   ...
}

for ob in scene:
ob
callbacks[ob.type](ri, ob, motion)  

5.  Finally see if we can get away from precaching motion.  Deformation seems broken.

**Comment by MWY3510** [comment]
That is ambitious for one weekend.

**Comment by bsavery** [comment]
Eh, it's mostly refractoring and moving stuff around, organizing.  But yes ;)

**Comment by bsavery** [comment]
Think I have everything mostly working.  Waaay faster ribgen

Before (on the gooseberry benchmark scene): ~12 min
After: < 3 min

**Comment by MWY3510** [comment]
Great that is wonderful news.

**Comment by AtomicPerception** [comment]
It does look like basic manual instancing is broken. Try this simple test. Take the default cube and duplicate it three times. Then take each cube and link it to a single instance of the cube mesh. Now export the scene and you will see that the code creates a new mesh for every cube instead of a single mesh RIB that is referenced multiple times. When evaluating objects take a look at the user count (ob.data.user). If this is greater than 1 then the object is an instance.

NOTE: Duplis seem to work correctly, it is only these maunally created instances that fall into this category.

I experienced an AddOn crash when there is no material applied to a lamp. 

I see a strange ALPHA whole in my final render?
![untitled-1](https://cloud.githubusercontent.com/assets/1889590/9038109/bc25da90-39bf-11e5-944a-fbca2463c085.jpg)

Nice work, the speed improvements are great!

**Comment by bsavery** [comment]
Hey AtomicP.  When you say "take each (duplicated) cube and link it to a single instance of the cube mesh" what do you mean (do you mean duplicating with ctrl + D)?  How do you link it?  Keep in mind I'm still a bit of a nOOb at driving blender.

If you could just attach the scene that would be great.  Also for the lamp which type?

**Comment by AtomicPerception** [comment]
I am not sure how to attach a BLEND scene here on GITHUB but I have placed one on the Renderman forums that you can pull down.
https://renderman.pixar.com/forum/showthread.php?s=&threadid=27835&perpage=25&pagenumber=11

This images shows how I manually created the instances in Blender.
![untitled-2](https://cloud.githubusercontent.com/assets/1889590/9040658/8615baee-39d1-11e5-870a-20315c5ee4d9.jpg)

NOTE: I also placed a few test scene on the renderman forum for regression testing. Mainly dupligroup and what not. Feel free to include them in the distro example folder if you find them useful.

**Comment by MWY3510** [comment]
Sorry this is off topic, but I will have AtomicP's testing scenes in today. And now resume talking about the issue at hand.

**Comment by bsavery** [comment]
atomicP.  I think the correct thing would just be to ri.ReadArchive the original/master mesh here no? We could do a whole object instance too I suppose... but that's more relevant for creating tons of instances which this it doesn't seem like you would use it for.

**Comment by bsavery** [comment]
Sorry to be more clear.  I think the solution here is we should be exporting the MESH to the archive not the object.  Then reference the mesh in the object block in rib:

static/my_mesh.rib:
PointsPolygons... 

in main rib:
AttributeBegin "Cube1"
Transform
#material for Cube1
ReadArchive "static/my_mesh.rib"
AttributeEnd

AttributeBegin "Cube2"
Transform
#material for Cube2
ReadArchive "static/my_mesh.rib"
AttributeEnd

This was actually how I had set up thing in the rewrite...
