### ISSUE TITLE
Blender crashes during render (not interactive)

### ISSUE THREAD

**Issue by Timaroberts** [bsavery/PRMan-for-Blender#91]
I just downloaded the PRMan addon today, and while rendering a scene Blender crashes repeatedly. I'm using ver. 2.75, not sure what to do to fix the issue.

**Comment by MWY3510** [comment]
What type of crash, as in what were you doing when it crashed?

**Comment by Timaroberts** [comment]
I was just rendering a simple scene, and I got an error message saying "PRMan exited", then within seconds Blender closed. It hasn't happened every time, but enough to be frustrating.

**Comment by AtomicPerception** [comment]
I just reviewed the current state of export.py an notice a that my function"RemoveMeshFromMemory" has been removed from export_polygon_mesh() and simply replaced with a one liner "bpy.data.meshes.remove(mesh)". This is very poor form and I even put comments in my code warning that if you don't excessively check to make sure that you are allowed to remove the mesh that Blender will crash.

The nature of bpy.data is somewhat buggy in the fact that your code can attempt to modify bpy.data at the "wrong" time. That is why you need to check the user count on every single mesh before you attempt to remove it. And if you can't remove it you need to leave it in memory or Blender will crash. Because what you are doing is creating what is called "stale data" inside of Blender. Then Blender attempts to act upon it but it does not exist anymore and that is what causes the crash.

While it is tempting to just throw my code away and think you are "optimizing" the process with one line of code you are just adding instability to the AddOn and creating future issues.

I suggest that you regress back to including RemoveMeshFromMemory and repairing export_polygon_mesh() with calls to this previous def.

**Comment by MWY3510** [comment]
Thanks AtomicP, I'll fix that today.

**Comment by MWY3510** [comment]
Ok, this issue is fixed. I will leave this open until Timaroberts has had a chance to test the changes. Thanks again AtomicP.

**Comment by bsavery** [comment]
AtomicP totally get what you're saying and understand that check.  Just to understand a bit more though, what other users of the mesh data?  My goal wasn't to think that I was optimizing by just cutting out lines of code.  

You'll also notice that we only use the meshes once, though, in that each instance of mesh data is exported once now.  So anyway while I can understand the added stability of adding checks like this, I'd like to understand more what other users of the data there are.   Any thoughts?

Brian

**Comment by AtomicPerception** [comment]
Sure, I have been programming the Blender API for years and have noticed that it does not always work as intended. So I have developed this style of code that over checks conditions to prevent crashing. I realize it may seem like a long hand approach to programming but in the case of remove mesh it is better to be safe than sorry. 

If you have not taken a look at the Gotchas page for the API, it is here:
http://www.blender.org/api/blender_python_api_2_75a_release/info_gotcha.html?highlight=remove%20mesh

While your code may be using the API in an ideal fashion, internally Blender may have held a lock on something due to timing (that is the best way I can describe it). Or the other way around. You remove a mesh without checking for user count and then a timing update occurs inside bpy.data and it is now referencing stale data.

I can not prove that the remove_mesh is causing Tim Roberts crash but when I took a look at the code and noticed that no safety check was in place for remove_mesh it kind of stood out to me.

In my mind, the relationship between blender python and bpy.data is kind of like the way a car engine works. The upper cam and the lower cam are kept in time by the timing belt. But in our programming model, the timing belt is virtual and is only in place at the start of the program, then it disappears and assume the both cams will spin at the same speed and remain in time. In theory this should work, but in practice I have experienced "timing slip".

I guess we need Tim's BLEND to really test one way or the other. Is he running an overclocked machine..?

**Comment by bsavery** [comment]
Thanks a ton.  Great info.

**Comment by Timaroberts** [comment]
I've had the same problem again today, and have noticed materials not rendering. I'm at a loss to be honest, to have such trouble with a simple scene. I also can't save the file anymore. I get an error message no matter what I do, changing render engine, closing Blender, etc.
![prman-test-scene-shot](https://cloud.githubusercontent.com/assets/13684082/9148087/7074e7fa-3d37-11e5-903c-d5a9c7dae319.png)

 Here's the .blend up to where I could last save.
https://drive.google.com/open?id=0B880NYmwQ_LEdDQyd0hUcGpNS1k

**Comment by MWY3510** [comment]
Hello Timaroberts,

I have reviewed the blend file you submitted and I have had no issues on my end. Are you using the latest version of the plugin?

Thank you,
MWY3510

**Comment by Timaroberts** [comment]
Yes MYW3510, I am. I just grabbed it day before yesterday, and today ran the repair on it. On small scenes it's doing better, but it still seems a little unpredictable with larger scenes. One in particular, and I'll upload when I'm able (on my phone at the moment), it crashes before it begins the render. Which is odd, because a similarly large scene from blend swap renders fine. Any ideas?

**Comment by MWY3510** [comment]
For the blend file can you also get me a screen grab of the console output during the error.

**Comment by Timaroberts** [comment]
Here's the blend file, https://drive.google.com/open?id=0B880NYmwQ_LEbWZBd2VkdHUyWDQ
and a screen grab of the error message. A lot of times, I don't get an error message however, Blender just closes. Thanks.
![prman-error](https://cloud.githubusercontent.com/assets/13684082/9156247/f86d2dcc-3e98-11e5-9016-ce1f8744404d.png)

**Comment by MWY3510** [comment]
Timaroberts, 

I don't have access to the blend file you posted. Google drive says that it is restricted.

MWY3510

**Comment by Timaroberts** [comment]
Sorry about that, should be accessible now.

**Comment by MWY3510** [comment]
Ok, I got the file. At the moment it looks like a geometry export issue. I will be back in a few hours to run more tests and possibly fix it.

**Comment by MWY3510** [comment]
I found the problem. The TV mesh had double vertices that caused the mesh exporter to error out. This problem I don't think can be truly fixed but a check should be in place to prevent a crash.

**Comment by bsavery** [comment]
Take a look at what the hair exporting code does. Something similar could
be done maybe there?  Or are al the vertices doubled?

On Sunday, August 9, 2015, MWY3510 <notifications@github.com> wrote:

> I found the problem. The TV mesh had double vertices that caused the mesh
> exporter to error out. This problem I don't think can be truly fixed but a
> check should be in place to prevent a crash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/91#issuecomment-129261361>
> .
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by Timaroberts** [comment]
I had a lot of doubled vertices in the scene, removed them and still having the same error. There's a delay in getting to the error, so maybe that's progress. I did notice that if my mouse moves at all, I get the "PRMan exited" error immediately. By the way, I want to say thanks for helping with this.

**Comment by MWY3510** [comment]
Thanks bsavery, I will try to look at this tomorrow.

**Comment by bsavery** [comment]
Here's the magic code that goes in subdiv/export polygon mesh.

primvars['P'] = P[:int(max(verts) + 1) * 3]

I guess we could do that by default.  It's a bit slower but safer.  Or do a try/except around the whole ri.PointsPolygond call.  But it fixes this issue of stray vertices.

Actually I think the best place to put it would be in the get_mesh method.

**Comment by bsavery** [comment]
Commited change.
